### ISSUE TITLE
"Selected $n words" popup can go off-screen

### ISSUE THREAD

**Issue by psvenk** [ecuber/excellentpoint#2]
When selecting a word or group of words that are on the left side of the input box, the "selected $n words" popup goes off-screen. This, of course, is a stylistic nitpick that does not affect functionality, but I figured that I would open an issue for it anyway. (In general, though, the UX is quite good.)

Screenshot:
![image](https://user-images.githubusercontent.com/45520974/111834839-8ae58100-88ca-11eb-9c66-ae0a4f6917cf.png)

**Comment by ecuber** [comment]
Thanks for bringing this up! I've noticed also that the position calculations get quite wonky for large displays. I'll get on it.
